name: Maven Central Deployment

on:
  push:
    tags:
      - 'v*'     # Trigger on version tags for releases
  workflow_dispatch: # Allow manual triggering of the workflow
    inputs:
      snapshot:
        description: 'Deploy SNAPSHOT version'
        required: false
        default: 'false'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          gpg-private-key: ${{ secrets.SEER_GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.SEER_GPG_PASSWORD }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Deploy to Maven Central
        if: startsWith(github.ref, 'refs/tags/')  # Only deploy releases to Maven Central
        run: mvn clean deploy --settings .github/maven/settings.xml
        env:
          OSSRH_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.SEER_GPG_PASSWORD }}

      - name: Deploy SNAPSHOT to OSSRH
        if: github.event.inputs.snapshot == 'true'  # Only deploy SNAPSHOTs when manually triggered
        run: mvn clean deploy --settings .github/maven/settings-snapshot.xml
        env:
          OSSRH_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
