name: Continuous Integration

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Set executable permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -B clean install

      - name: Run Sonar
        run: ./mvnw -B sonar:sonar -Dsonar.projectKey=imsweb_reportability-screener -Dsonar.organization=imsweb -Dsonar.host.url="https://sonarcloud.io" -Dsonar.token=${{ secrets.SONAR_TOKEN }}

