name: Maven Central Deployment

on:
  repository_dispatch:
    types: manual-publish
  release:
    types: [ created ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'maven'
          gpg-private-key: ${{ secrets.SEER_GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.SEER_GPG_PASSWORD }}

      - name: Set executable permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Deploy to Maven Central
        if: startsWith(github.ref, 'refs/tags/')  # Only deploy releases to Maven Central
        run: ./mvnw -B clean deploy nexus-staging:release -P release --settings .github/maven/settings.xml
        env:
          OSSRH_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.SEER_GPG_PASSWORD }}
