name: Maven Central Deployment

on:
  push:
    tags:
      - 'v*'     # Trigger on version tags for releases

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          gpg-private-key: ${{ secrets.SEER_GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.SEER_GPG_PASSWORD }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Set executable permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Deploy to Maven Central
        if: startsWith(github.ref, 'refs/tags/')  # Only deploy releases to Maven Central
        run: ./mvnw clean deploy --settings .github/maven/settings.xml
        env:
          OSSRH_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.SEER_GPG_PASSWORD }}
