name: Maven Central Deployment

env:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Djava.awt.headless=true"

on:
  push:
    tags:
      - 'v*'     # Trigger on version tags for releases

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
          gpg-private-key: ${{ secrets.SEER_GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.SEER_GPG_PASSWORD }}

      - name: Set executable permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Deploy to Maven Central
        if: startsWith(github.ref, 'refs/tags/')  # Only deploy releases to Maven Central
        run: ./mvnw -B clean deploy --settings .github/maven/settings.xml
        env:
          OSSRH_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.SEER_GPG_PASSWORD }}
