name: Release Snapshot

env:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Djava.awt.headless=true"

on:
  workflow_dispatch:
    inputs:
      snapshotVersion:
        description: 'Snapshot version'
        required: true
        default: '1.0.0-SNAPSHOT'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Set executable permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build and Deploy Snapshot
        run: |
          ./mvnw -B versions:set -DnewVersion=${{ github.event.inputs.snapshotVersion }}
          ./mvnw -B clean deploy --settings .github/maven/settings-snapshot.xml
        env:
          OSSRH_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
